sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: slVmTIAQTemg7sYZplkoA90W/bbFRqTcw0G0ZF+qdJJdvac4JYGpNabCQMhf+h/lqx2lAccuZ6Y0K+Sg8moTrR+9RzQ34I4uCZwQlXesJXgzAfLWw7G9qzR1OGfLxzt83Fhi9xefpqhb94V3SrdGLi7wLhBZZZ/DJc1I3xnRU3NIqE6/OEdNUv8IdQOc5LZgzpmX7SYe4SGpfAxxzmwNefTfajPPgDmzohp1aUZcJT+qH9XR84DhwDZfmqA7NDAxc4WBDGbrsEnIiUW+zbczxBuOKbrhNwFnZyOqlaQy+ubMy6nlBaKjSmK/XLmgPgtb2EOphZ+XMI4auzN+U8LsZRhvzGK1P8ExafEJHdGG/esu2YPWwCsD/tpyrGjIWUuJeVZUHauKwEhDA8byYeT1k+iN2MY1kCxFWA/np1mZev0bZOBdQus/kWzvkgjwfGVL6sUA/YjBB+GvicEJqflkMboCiWm90t71thfJgldlRs1aGDhXzZybnnlpJAX+ZVTOmC8cD411NwGSFOqxvwtKcldIY0kHTTB/6vtVpaE+h6rGQ900dpsraaJ2O+pIbInNc6WY1Vhkoi/v29I55AdwwnFAa3oRlg5Ntk2MIaTnr++4XbN9Qdo+HqyMuUllArUmZ3BC9+zg0O15l+tbaSmHU5N9I+OpV3Zlb+ufrtuNRD4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Tales-of-Unrest_1202
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy